boxplot(datasets7$Konkurent,datasets7$Cena)
boxplot(datasets7$Distance,datasets7$Cena)
boxplot(datasets7$Peoples,datasets7$Cena)
boxplot(datasets7$Average,datasets7$Cena)
plot(datasets7$Konkurent,datasets7$Cena)
plot(datasets7$Distance,datasets7$Cena)
plot(datasets7$Peoples,datasets7$Cena)
plot(datasets7$Average,datasets7$Cena)
cor(datasets7)
library(corrgram)
corrgram(datasets7, order=TRUE, lower.panel=panel.shade,upper.panel=panel.pie,main="Коррелограмма")
cholod<-lm(Cena~Konkurent+Distance+Peoples+Average+Largema,data=datasets7)
vif(cholod)
sqrt(vif(cholod))>2
price<-lm(Cena~Konkurent+Distance+Peoples+Average+Largema,data=datasets7)
summary(price)
price<-lm(Cena~Konkurent+Distance+Peoples+Average+Largema,data=datasets7)
price2<-lm(Cena~Konkurent+Distance+Peoples+Largema,data=datasets7)
AIC(price,price2)
stepAIC(price,direction="backward")
anova(price2)   
price<-lm(Cena~Konkurent+Distance+Peoples+Average+Largema,data=datasets7)
library(car)
durbinWatsonTest(price)
ncvTest(price)
pricet<-as.data.frame(scale(datasets7))
pricej<-lm(Cena~Konkurent+Distance+Peoples+Average+Largema,data=pricet)
coef(pricej)
centis<-lm(Cena~Konkurent+Distance+Peoples+Average,data=datasets77)
predict(centis)
predict(centis,interval="prediction")



